[2024-04-30T20:43:15.527+0000] {scheduler_job_runner.py:780} ERROR - Executor reports task instance <TaskInstance: homework2_data_pipeline_demo.data_acquisition__1 manual__2024-04-30T20:30:41.382358+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
[2024-04-30T20:43:26.890+0000] {scheduler_job_runner.py:780} ERROR - Executor reports task instance <TaskInstance: homework2_data_pipeline_demo.data_acquisition__1 manual__2024-04-30T20:30:41.382358+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
